
tag_prefix = "v"

pre_bump_hooks = [
  "npm run build",
  "npm run test",
  "npm version --no-commit-hooks --no-git-tag-version {{version}}",
  "git add package.json package-lock.json"
]

post_bump_hooks = [
  "git push",
  "git push origin v{{version}}",
  "npm publish"
]

# Install these hooks with `cog install-hook --all`

[git_hooks.pre-commit]
script = """#!/bin/sh
set -e
"""

[git_hooks.commit-msg]
script = """#!/bin/sh
set -e
cog verify --file $1
"""
