# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: E2E Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20.x]
        arch: [x64]

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} / Node ${{ matrix.node-version }} ${{ matrix.arch }}

    permissions:
      contents: read
      packages: read

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Log in to GHCR.io
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Prepare environment for E2E tests
      run: sh e2e-tests-prep.sh

    - name: Run E2E tests
      run: sh e2e-tests-run.sh

    - name: Clean up environment after E2E tests
      run: sh e2e-tests-clean.sh
